---
AWSTemplateFormatVersion: 2010-09-09
Description: WhatFood Today Default EC2_Layer Template for the Project

Parameters:
  ProjectName:
    Type: String
    Description: Project Name
    Default: wft
  RdsRegion:
    Type: String
    Default: ap-northeast-2
  RegionName:
    Type: String
    Description: Region Name
    AllowedValues:
      - seoul
      - tokyo

Mappings:
  CidrMap:
    ap-northeast-2:
      VpcCidr: 172.16.0.0/16
      PubSn1Cidr: 172.16.1.0/24
      PubSn2Cidr: 172.16.2.0/24
      WebSn3Cidr: 172.16.3.0/24
      WebSn4Cidr: 172.16.4.0/24
      RdsSn5Cidr: 172.16.5.0/24
      RdsSn6Cidr: 172.16.6.0/24
    ap-northeast-1:
      VpcCidr: 172.17.0.0/16
      PubSn1Cidr: 172.17.1.0/24
      PubSn2Cidr: 172.17.2.0/24
      WebSn3Cidr: 172.17.3.0/24
      WebSn4Cidr: 172.17.4.0/24
  AmiMap:
    ap-northeast-2:
      Ami: ami-0c2ec5caea5a1a1ab
    ap-northeast-1:
      Ami: ami-0b53194d9d4d5cfea

Resources:
# Web Application Load Balancer & Security Group
  WebAlbSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue VpcId
      GroupDescription: !Sub "${AWS::Region} Web ALB Security Group"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key : Name
          Value : !Sub "${RegionName}-${ProjectName}-web-alb-sg"

  WebAlb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Name: !Sub "${RegionName}-${ProjectName}-web-alb"
      SecurityGroups:
        - !Ref WebAlbSg
      Subnets:
        - !ImportValue PubSn1Id
        - !ImportValue PubSn2Id

  WebAlbTg:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${RegionName}-${ProjectName}-web-tg"
      Port: 80
      Protocol: HTTP
      HealthCheckPath: '/'
      HealthCheckIntervalSeconds: 10
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      VpcId: !ImportValue VpcId
      TargetGroupAttributes:
        - Key: stickiness.enabled
          Value: true
        - Key: stickiness.type
          Value: lb_cookie
        - Key: stickiness.lb_cookie.duration_seconds
          Value: 3600
      Tags:
        - Key : Name
          Value : !Sub "${RegionName}-${ProjectName}-web-tg"

  WebAlbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref WebAlbTg
      LoadBalancerArn: !Ref WebAlb
      Port: 80
      Protocol: HTTP

# LaunchTemplate & Security Group
  WebSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue VpcId
      GroupDescription: !Sub "${AWS::Region} Web Instance Security Group"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !FindInMap [CidrMap, ap-northeast-2, PubSn2Cidr]
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref WebAlbSg
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId: !Ref WebAlbSg
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 10.0.0.0/8
      Tags:
        - Key : Name
          Value : !Sub "${RegionName}-${ProjectName}-web-sg"

  WebRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: SSMReadPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource:
                  - !Sub arn:aws:ssm:${RdsRegion}:${AWS::AccountId}:parameter/db_password
                  - !Sub arn:aws:ssm:${RdsRegion}:${AWS::AccountId}:parameter/db_host
                  - !Sub arn:aws:ssm:${RdsRegion}:${AWS::AccountId}:parameter/wft-api-key

  WebInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref WebRole

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub "${ProjectName}-lt"
      VersionDescription: version 1.0
      LaunchTemplateData:
        ImageId: !FindInMap [AmiMap, !Ref "AWS::Region", Ami]
        InstanceType: t3.micro

        IamInstanceProfile:
          Name: !Ref WebInstanceProfile

        KeyName: !Sub "${RegionName}-${ProjectName}-key"
        SecurityGroupIds:
          - !Ref WebSg
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            DB_HOST=$(aws ssm get-parameter --name "db_host" --query "Parameter.Value" --output text --region ${RdsRegion})
            DB_PASS=$(aws ssm get-parameter --name "db_password" --with-decryption --query "Parameter.Value" --output text --region ${RdsRegion})
            echo "DB_HOST=$DB_HOST" > /var/www/db_config.ini
            echo "DB_PASSWORD=$DB_PASS" >> /var/www/db_config.ini
            chmod 600 /var/www/db_config.ini
            chown apache:apache /var/www/db_config.ini
            wget https://github.com/wisdompjt-wft/aws-wft-project/raw/main/init_db.php
            sed -i "s/DirectoryIndex index.html/DirectoryIndex index.php index.html/g" /etc/httpd/conf/httpd.conf
            sed -i "s/127.0.0.1/${RDS_ENDPOINT}/g" db.php
            sed -i "s/= '1234';/= '$DB_PASS';/g" db.php
            systemctl start httpd
            systemctl enable httpd
            php /var/www/html/init_db.php
            rm -f /var/www/html/init_db.php
# sed -i "s/localhost/${RdsDns}/g" config.php

# Auto Scaling Group & Scaling Policy
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub "${RegionName}-${ProjectName}-asg"
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      VPCZoneIdentifier:
        - !ImportValue WebSn3Id
        - !ImportValue WebSn4Id
      TargetGroupARNs:
        - !Ref WebAlbTg
      DesiredCapacity: 2
      MinSize: 2
      MaxSize: 4

  ScalingPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: 50
...
